# 
# Do not Edit! Generated by:
# spectacle version 0.18
# 
# >> macros
# << macros

Name:       xorg-x11-utils-xhost
Summary:    X.Org X11 xhost utility
Version:    1.0.3
Release:    1
Group:      System/X11
License:    MIT/X11
URL:        http://www.x.org
Source0:    ftp://ftp.x.org/pub/individual/app/xhost-%{version}.tar.bz2
Source100:  xorg-x11-utils-xhost.yaml
BuildRequires:  pkgconfig(x11)
BuildRequires:  pkgconfig(xmuu)
BuildRequires:  pkgconfig(xau)
BuildRequires:  pkgconfig


%description
Description: %{summary}



%prep
%setup -q -n xhost-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install 

# >> install post
# << install post






%files
%defattr(-,root,root,-)
# >> files
/usr/bin/xhost
%doc /usr/share/man/man1/xhost.1.gz
# << files


